title: "Back-End Engineering Curriculum - Turing School of Software and Design"
description: "Open source curriculum for the Turing School of Software and Design's back end engineering program."
url: "https://s-espinosa.github.io/blank/"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

plugins:
  - jemoji
